### ISSUE TITLE
Request module is used in (lib/rave.base.js), but Axios was included as a dependency 

### ISSUE THREAD

**Issue by alob-mtc** [Flutterwave/Flutterwave-node-v3#11]
```sh
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'request'
Require stack:
- /home/kira/Desktop/node-app/flutter-rave/node_modules/flutterwave-node-v3/lib/rave.base.js
- /home/kira/Desktop/node-app/flutter-rave/node_modules/flutterwave-node-v3/index.js
- /home/kira/Desktop/node-app/flutter-rave/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/kira/Desktop/node-app/flutter-rave/node_modules/flutterwave-node-v3/lib/rave.base.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/kira/Desktop/node-app/flutter-rave/node_modules/flutterwave-node-v3/lib/rave.base.js',
    '/home/kira/Desktop/node-app/flutter-rave/node_modules/flutterwave-node-v3/index.js',
    '/home/kira/Desktop/node-app/flutter-rave/app.js'
  ]
}

```
This is the error throw anytime i try to call any of the APIs.
**Request** was used as the HTTP client in the lib/rave.base.js, but **Axios** was included as the HTTP client in the package.json

**Comment by gal1l0** [comment]
Me too am having this issue
![image](https://user-images.githubusercontent.com/48126545/87005537-6f649b00-c1bf-11ea-9111-b17dc27b63b2.png)
