### ISSUE TITLE
Test script throwing error

### ISSUE THREAD

**Issue by alob-mtc** [Flutterwave/Flutterwave-node-v3#13]
Getting this error anytime i try to run the test suit
```sh
/home/kira/Desktop/git/Flutterwave-node-v3/lib/rave.utils.js:8
		throw new error(message);
		^

Error: Public Key required
    at Object.RaveUtils.emptyCheck (/home/kira/Desktop/git/Flutterwave-node-v3/lib/rave.utils.js:8:9)
    at new RaveBase (/home/kira/Desktop/git/Flutterwave-node-v3/lib/rave.base.js:6:12)
    at Suite.<anonymous> (/home/kira/Desktop/git/Flutterwave-node-v3/test/rave.bank.test.js:23:20)
    at Object.create (/home/kira/Desktop/git/Flutterwave-node-v3/node_modules/mocha/lib/interfaces/common.js:112:19)
    at context.describe.context.context (/home/kira/Desktop/git/Flutterwave-node-v3/node_modules/mocha/lib/interfaces/bdd.js:40:27)
    at Object.<anonymous> (/home/kira/Desktop/git/Flutterwave-node-v3/test/rave.bank.test.js:17:1)

```

**Comment by mikey247** [comment]
@alob-mtc @Corvus97  how did you solve this please I'm having the same error

**Comment by alob-mtc** [comment]
To test you need to make use of a test PUBLIC_KEY and SECRET_KEY, this would be documented properly for easier contribution in the future. You can also raise a PR to address this.

**Comment by mikey247** [comment]
Thanks I already sorted it out, I set my .env configuration after calling the flutterwave class.

**Comment by mikey247** [comment]
I'm currently getting 502 errors when I make requests, it's returned html of a heroku app landing page, any idea what could be the matter???

**Comment by alob-mtc** [comment]
There might be a downtime, you can try again after a couple of minutes or hours.

**Comment by mikey247** [comment]
It's been like this for days, I've sent emails but no response.
